services:
  backend:
    build:
      context: backend
      target: dev-envs
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
      - frontnet
      
  tests:
    build: tests
    depends_on: 
      - backend
      - proxy
    networks:
      - frontnet
    profiles:
      - testing
    volumes:
      - ./tests/:/tests

networks:
  backnet:
  frontnet:
